name: test_project
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  build_runner: ^2.3.3
  dart_frog: ^0.3.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
